name: CICD-deploy
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: claire-eee/meju-test
          token: ${{ secrets.TOKEN }}
          path: meju-test
          
      - name: Extract last 5 characters of GITHUB_SHA
        run: |
          SHA_SHORT=${GITHUB_SHA: -5}
          echo "RELEASE_VERSION=$SHA_SHORT" >> $GITHUB_ENV
      - name: Modify YAML file in the yaml folder
        run: |
          cd meju-test/was
          kustomize edit set image was-image=${{ secrets.DOCKERHUB_USERNAME }}:v${{ env.RELEASE_VERSION }}
          
      - name: Commit and Push
        run: |
          cd meju-test
          git config --global user.email '${{ secrets.G_EMAIL }}'
          git config --global user.name '${{ secrets.G_NAME }}'
          git add .
          git commit -m "Update YAML tag to ${{ env.RELEASE_VERSION }}"
          git push
      - name: Notify Discord on Success
        if: success()
        uses: Sniddl/discord-commits@v1.6
        with:
          message: "CD 테스트 배포가 성공했습니다. ${{ github.run_id }}"
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
  
      - name: Notify Discord on Failure
        if: failure()
        uses: Sniddl/discord-commits@v1.6
        with:
          message: "CI 테스트 배포가 실패했습니다. ${{ github.run_id }}"
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}         
